apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-demo-backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-demo-frontend
automountServiceAccountToken: false
